### ISSUE TITLE
Use config.php from igo repo

### ISSUE THREAD

**Issue by tremblaysimon** [infra-geo-ouverte/puppet-igo#10]
Puisque nous avons dupliqué le config.php, cela fait en sorte que le module d'installation n'est pas synchronisé automatiquement avec toutes modifications de celui-ci dans le dépôt igo. 

Il faut alors utiliser directement le fichier fourni par le dépôt igo plutôt que de le dupliquer dans ce dépôt-ci.

**Comment by mbarbeau** [comment]
+1
On utilise l'authentificationMSP dans le template alors que la classe n'existe pas dans le dépôt public de IGO.

**Comment by clauded** [comment]
Vous devriez monter la version du module à 1.3...

**Comment by tremblaysimon** [comment]
C'est fait! Et maintenant on utilise le fichier de config exemple simple provenant du dépôt IGO. On peut continuer d'utiliser quand même notre propre fichier de template par contre! Voir #12.

Et l'intégration de Travis CI est faite (puppet-lint est exécuté pour valider le code), c'est une première étape.
